global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alerts/prometheus-alerts.yml"

scrape_configs:
  - job_name: 'surgeopt'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 10s
    metrics_path: /metrics
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
