name: Minimal CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies for confluent-kafka
      run: |
        sudo apt-get update
        sudo apt-get install -y librdkafka-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8

    - name: Quick lint check (errors only)
      run: |
        flake8 src tests --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run basic tests
      run: |
        pytest tests/test_basic.py -v --tb=short

